# Generated by Django 5.0.4 on 2024-05-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('product_info', models.TextField(blank=True, null=True, verbose_name='Product Information')),
                ('price', models.FloatField(verbose_name='Product Price')),
                ('discaunt_price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Product Discaunt Price')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
