# Generated by Django 5.0.4 on 2024-05-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='abability',
            field=models.CharField(blank=True, choices=[('In Stock', 'In Stock'), ('Stock Out', 'Stock Out')], max_length=50, null=True),
        ),
    ]
