# Generated by Django 5.0.4 on 2024-05-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_abability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('valid_date', models.DateField()),
                ('valid_form', models.DateField()),
                ('discaunt', models.FloatField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
