# Generated by Django 5.0.4 on 2024-05-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('information', models.TextField()),
                ('image', models.ImageField(upload_to='Service')),
            ],
        ),
    ]
