# Generated by Django 5.0.4 on 2024-05-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_ourservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('information', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='Blog')),
                ('post', models.DateField()),
            ],
        ),
    ]
